**1. What is Numpy and how is it different from Python List?**

Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Advantages of using Numpy Arrays Over Python Lists:

    Consumes less memory.
    Fast as compared to the python List.
    Convenient to use.
#NumPy arrays store elements of the same data type, making them more compact and memory-efficient than lists.

#Lists can hold different data types, but this can decrease memory efficiency and slow numerical operations.

**2.How do you create a Numpy array?**

A Numpy array is a data structure that stores multiple values of the same type in a single variable.
To create a NumPy array, We use the function np.array() . 

In [12]:
import numpy as np

a = np.array([1,2,3])  # Create a 1D array
b = np.array([[1,2,3], [4,5,6]])    # Create a 2D array
c = np.array([[[1,2,3] , [4,5,6]],[[7,8,9] , [10,11,12]]])   #create a 3D array
print(a)
print(b)
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


**3.Explain the concept of broadcasting in numpy array**

Broadcasting happened because of miss match in array Dimension.
Broadcasting is a term that describes how NumPy handles arithmetic operations between arrays with different shapes. It allows you to perform element-wise operations without explicitly looping over the arrays. For example, you can multiply a scalar value by an array, or add two arrays of different sizes, as long as they are compatible for broadcasting.
the smaller array is broadcast across the larger array so that they have compatible shapes. 

In [13]:
a = np.array([2,3,4])
b = 10
print(a+b)

[12 13 14]


**4. How do you perform element wise addition of two numpy arrays**

To perform element-wise addition of two numpy arrays in Python, We use the numpy.add() function or the + operator. Both methods return a new numpy array with the result of the addition. The two arrays must have the same shape or be broadcastable to a common shape.

In [14]:
a = np.array([1,2,3])
b = np.array([10,20,30])
c = np.add(a,b)
print(c)

[11 22 33]


**5. How do you reshape a numpy array?**

NOTE --> Reshaping data in numpy with (-1,1) means that we want to reshape an array into a new array with one column and as many rows as needed to preserve the number of elements.
we can also use (1,-1) to convert a 1D array into a 2D row vector.

In [15]:
array = np.array([1, 2, 3, 4, 5, 6])
# reshape to 2 rows and 3 columns
reshaped = array.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [16]:
#We can also use -1 as one of the dimensions to let numpy infer the value from the other dimensions
reshaped = array.reshape(3, -1)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
reshaped = array.reshape(2, -1)
print(reshaped)

[[1 2 3]
 [4 5 6]]


**6. what is the difference b/w np.dot and np.matmul in numpy**

i)numpy.matmul() supports multiplication by scalars but numpy.dot() doesn’t.

ii) they treat N-D array in different ways


NOTE--> Both of numpy.multiply() and * multiply numpy.ndarray arguments element-wise.
However, in the case of numpy.matrix objects, numpy.multiply() does element-wise multiplication but * does conventional matrix multiplication.

**np.dot()**

If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

**7. How can you find maximum and minimum values in numpy array?**


In [19]:
arr = np.array ( [ [11, 2, 3], [4, 5, 16], [7, 81, 22]])
print(np.max(arr))  # max element in the whole array

print(np.min(arr))   ## min element in the whole array
print(np.max(arr, axis=0)) # maximum elements in the columns of the array 
print(np.min(arr, axis=1)) #minimum elements in the rows of the array



81
2
[11 81 22]
[2 4 7]


In [22]:
# creating two single dimensional array
a = np.array([1, 4, 6, 8, 9])
b = np.array([5, 7, 3, 9, 22])
 
# print maximum value
print(np.maximum(a, b))

#list containing maximum values from each column.

[ 5  7  6  9 22]


**8. Explain the use of Numpy's Random module for generating random numbers**

Numpy’s Random module is a collection of functions that can generate random numbers from various probability distributions. Random numbers are useful for many applications data analysis, and machine learning.

Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

In [23]:
#Generate a random integer from 0 to 100:

from numpy import random
x = random.randint(100)
print(x)

95


In [24]:
# Generate a random float from 0 to 1:
y = random.rand()
print(y)

0.8425774372730614


In [31]:
# enerate a 1-D array containing 5 random integers from 0 to 100:
from numpy import random
x = random.randint(100, size = (5))     #size parameter to specify the shape of the array.
print(x)

[60 80 12 90 68]


In [30]:
# Generate a 2-D array with 2 rows, each row containing 5 random integers from 0 to 100:

from numpy import random
z = random.randint(100, size = (2,5))
print(z)

[[73 90 34 55 44]
 [44 97  3 85 26]]
